<a href="https://colab.research.google.com/github/GeorgeNagib/AI-Course/blob/main/Linear_Regression_Appartments.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv("./gld_price_data.csv")

In [4]:
data

Date          SPX         GLD        USO      SLV   EUR/USD
0      1/2/2008  1447.160034   84.860001  78.470001  15.1800  1.471692
1      1/3/2008  1447.160034   85.570000  78.370003  15.2850  1.474491
2      1/4/2008  1411.630005   85.129997  77.309998  15.1670  1.475492
3      1/7/2008  1416.180054   84.769997  75.500000  15.0530  1.468299
4      1/8/2008  1390.189941   86.779999  76.059998  15.5900  1.557099
...         ...          ...         ...        ...      ...       ...
2285   5/8/2018  2671.919922  124.589996  14.060000  15.5100  1.186789
2286   5/9/2018  2697.790039  124.330002  14.370000  15.5300  1.184722
2287  5/10/2018  2723.070068  125.180000  14.410000  15.7400  1.191753
2288  5/14/2018  2730.129883  124.489998  14.380000  15.5600  1.193118
2289  5/16/2018  2725.780029  122.543800  14.405800  15.4542  1.182033

[2290 rows x 6 columns]

In [28]:
X = data.iloc[:, [1,3,4,5]].to_numpy()
Y = data.iloc[:, [2]].to_numpy()

array([[ 84.860001],
       [ 85.57    ],
       [ 85.129997],
       ...,
       [125.18    ],
       [124.489998],
       [122.5438  ]])

In [29]:
model = LinearRegression()

In [30]:
model.fit(X,Y)

LinearRegression()

In [32]:
X[0]

array([1447.160034,   78.470001,   15.18    ,    1.471692])

In [33]:
Y[8]

array([89.540001])

In [34]:
model.predict([ [5005, 75, 21, 1.08] ])

array([[139.2618192]])